#!/bin/sh 
# /etc/init.d/cstaserve 
# Author: Marcelo Mariano 
# 
start() { 
/home/marcelo/Projects/workspace/CstaApp/Debug/CstaApp -d 
} 
stop() { 
 kill -9 `pgrep CstaApp` 2>/dev/null 
} 
case $1 in 
 start) 
   start 
 ;; 
 stop)
   stop 
 ;; 
 restart) 
   stop 
   sleep 1 
   start 
 ;; 
 *) 
 echo "Usage: $0 start|stop|restart" 
 exit 1 
 ;; 
 esac 
